FROM mcr.microsoft.com/devcontainers/base:debian

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends texlive texlive-lang-portuguese texlive-fonts-extra texlive-latex-extra texlive-science latexmk
